# Numpy Mdule

In [1]:
import numpy as np

In [2]:
my=[1,2,3,4,5]
arr=np.array(my)
print(arr)

[1 2 3 4 5]


In [3]:
print(type(arr))

<class 'numpy.ndarray'>


In [5]:
arr.shape

(5,)

In [8]:
my1=[5,6,7,8,9]
my2=[0,9,8,7,6]
arr=np.array([my,my1,my2])
print(arr)

[[1 2 3 4 5]
 [5 6 7 8 9]
 [0 9 8 7 6]]


In [10]:
arr.shape

(3, 5)

In [13]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 5],
       [6, 7, 8],
       [9, 0, 9],
       [8, 7, 6]])

In [14]:
arr

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9],
       [0, 9, 8, 7, 6]])

In [15]:
arr.T

array([[1, 5, 0],
       [2, 6, 9],
       [3, 7, 8],
       [4, 8, 7],
       [5, 9, 6]])

In [17]:
arr[1,3]

8

In [18]:
arr[:,3]

array([4, 8, 7])

In [19]:
arr[0:2,3]

array([4, 8])

In [20]:
arr[1:,3:]

array([[8, 9],
       [7, 6]])

In [22]:
np.linspace(1,3,5)

array([1. , 1.5, 2. , 2.5, 3. ])

In [36]:
arr

array([[500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500]])

In [37]:
arr[2:]=100
arr

array([[500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500],
       [100, 100, 100, 100, 100]])

In [38]:
arr[1:]=100
arr

array([[500, 500, 500, 500, 500],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])