### sequence data set

In [1]:
mynm="DAKAMARI VASU"  #normal string
print(mynm)

DAKAMARI VASU


In [3]:
myfamilynm=["Vasu","govind","Varalakshmi","lavanya"]  #Creating a list multi strings
myclg=["vasu",55,"tanush",51,55,51,13,43]   #string can have dublictae values also
print(myfamilynm)
print(myclg)

['Vasu', 'govind', 'Varalakshmi', 'lavanya']
['vasu', 55, 'tanush', 51, 55, 51, 13, 43]


In [6]:
from array import *  #importing the arrays module
samplearray= array("i",[1,2,3,4,5,6,7,8,9,0]) #insilising the array
print(samplearray)
for x in samplearray : print(x)


array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9, 0])
1
2
3
4
5
6
7
8
9
0


# Numpy

In [1]:
#creating a numpy array
my_list=[1,2,3,4,5,6]
import numpy as np
array=np.array(my_list,dtype=int)
print(array)

[1 2 3 4 5 6]


In [2]:
print(len(array)) # length of array
print(type(array))# tupe of the array
print(array.ndim)# diamenstions of the array
print(array.shape)# shape of array
arr=array.reshape(3,2) #reshaping the array
print(arr)
print(arr.shape)


6
<class 'numpy.ndarray'>
1
(6,)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [19]:
import numpy as np
lst1=[1,2,3,4,5,6,7,8,9,0]
lst2=[1,2,3,4,5,6,7,8,9,0]
lst3=[1,2,3,4,5,6,7,8,9,0]
arr=np.array([lst1,lst2,lst3])
print("the normal arraya is :",arr)
print("the Type arraya is :",type(arr))
print("the length arraya is :",len(arr))
print("the diamensions of arraya is :",arr.ndim)
print("the shape of arraya is :",arr.shape)
arr1=array.reshape(3,2)
print("the new arraya is :",arr1)
print("the new reshape arraya is :",arr1.shape)
a=np.arange(26)
print(a)

the normal arraya is : [[1 2 3 4 5 6 7 8 9 0]
 [1 2 3 4 5 6 7 8 9 0]
 [1 2 3 4 5 6 7 8 9 0]]
the Type arraya is : <class 'numpy.ndarray'>
the length arraya is : 3
the diamensions of arraya is : 2
the shape of arraya is : (3, 10)
the new arraya is : [[1 2]
 [3 4]
 [5 6]]
the new reshape arraya is : (3, 2)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25]


# pandas

In [3]:
import os
import pandas as pd
data_frame = pd.read_csv("D:\machinelearning\employees.csv")
print(data_frame)

    employ_id   first_name    last_name     email        phone_number  \
0         100       Steven         King     SKING        515.123.4567   
1         101        Neena      Kochhar  NKOCHHAR        515.123.4568   
2         102          Lex      De Haan   LDEHAAN        515.123.4569   
3         103    Alexander       Hunold   AHUNOLD        590.423.4567   
4         104        Bruce        Ernst    BERNST        590.423.4568   
5         105        David       Austin   DAUSTIN        590.423.4569   
6         106        Valli    Pataballa  VPATABAL        590.423.4560   
7         107        Diana      Lorentz  DLORENTZ        590.423.5567   
8         108        Nancy    Greenberg  NGREENBE        515.124.4569   
9         109       Daniel       Faviet   DFAVIET        515.124.4169   
10        110         John         Chen     JCHEN        515.124.4269   
11        111       Ismael      Sciarra  ISCIARRA        515.124.4369   
12        112  Jose Manuel        Urman   JMURMAN  

In [4]:
samp=data_frame.copy(deep=True)
print(samp)

    employ_id   first_name    last_name     email        phone_number  \
0         100       Steven         King     SKING        515.123.4567   
1         101        Neena      Kochhar  NKOCHHAR        515.123.4568   
2         102          Lex      De Haan   LDEHAAN        515.123.4569   
3         103    Alexander       Hunold   AHUNOLD        590.423.4567   
4         104        Bruce        Ernst    BERNST        590.423.4568   
5         105        David       Austin   DAUSTIN        590.423.4569   
6         106        Valli    Pataballa  VPATABAL        590.423.4560   
7         107        Diana      Lorentz  DLORENTZ        590.423.5567   
8         108        Nancy    Greenberg  NGREENBE        515.124.4569   
9         109       Daniel       Faviet   DFAVIET        515.124.4169   
10        110         John         Chen     JCHEN        515.124.4269   
11        111       Ismael      Sciarra  ISCIARRA        515.124.4369   
12        112  Jose Manuel        Urman   JMURMAN  

In [4]:
import os
import pandas as pd
data_frame = pd.read_csv("D:\machinelearning\employees.csv")
print(data_frame)

    employ_id   first_name    last_name     email        phone_number  \
0         100       Steven         King     SKING        515.123.4567   
1         101        Neena      Kochhar  NKOCHHAR        515.123.4568   
2         102          Lex      De Haan   LDEHAAN        515.123.4569   
3         103    Alexander       Hunold   AHUNOLD        590.423.4567   
4         104        Bruce        Ernst    BERNST        590.423.4568   
5         105        David       Austin   DAUSTIN        590.423.4569   
6         106        Valli    Pataballa  VPATABAL        590.423.4560   
7         107        Diana      Lorentz  DLORENTZ        590.423.5567   
8         108        Nancy    Greenberg  NGREENBE        515.124.4569   
9         109       Daniel       Faviet   DFAVIET        515.124.4169   
10        110         John         Chen     JCHEN        515.124.4269   
11        111       Ismael      Sciarra  ISCIARRA        515.124.4369   
12        112  Jose Manuel        Urman   JMURMAN  

In [14]:
rollno=pd.read_excel("AIML_rolls.xls")
rollno

AIML-  I Sem (Section - A)  Unnamed: 1                    Unnamed: 2  \
51                         51  20951A6651  PENNABADI TANUSH KUMAR REDDY   
52                         52  20951A6652         VEMULAPALLY TEJASWINI   
53                         53  20951A6653              JAKKAMPUDI VARUN   
54                         54  20951A6654                  VEERLA VARUN   
55                         55  20951A6655                 DAKAMARI VASU   
56                         56  20951A6656           GUMMADAVELLI NIKHIL   
57                         57  20951A6657          DASARI VENKATA AKHIL   
58                         58  20951A6658     KALLAGUNTA VISHNU VARDHAN   
59                         59  20951A6659                SURGI YASHASRI   
60                         60  20951A6660       NALLOJU YASHWANTH KUMAR   

                     Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7  \
51  PENNABADI MADHUSUDANA REDDY          M       AIML         34          1   
52     VEMULAPALLY SRINIVAS RAO          F       AIML         34          1   
53             JAKKAMPUDI VINOD          M       AIML         34          1   
54           VEERLA KIRAN KUMAR          M       AIML         34          1   
55             DAKAMARI GOVINDU          M       AIML         34          1   
56         GUMMADAVELLI RATHISH          M       AIML         34          1   
57         DASARI VENKATESWARLU          M       AIML         34          1   
58           KALLAGUNTA MADHAVA          M       AIML         34          1   
59               SURGI JANGAIAH          F       AIML         34          1   
60      NALLOJU JAGADEESH KUMAR          M       AIML         34          1   

   Unnamed: 8 Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12 Unnamed: 13  \
51          A        338           M          OC  9391366042  8096344455   
52          A        338           M          OC  9110399068  9440607936   
53          A        338           M          OC  7337530755  7075226909   
54          A        338           M        BC-D  8106409349  8019172876   
55          A        338           C        BC-A  9392883297  9948923528   
56          A        338           M          OC  9000079398  9849067328   
57          A        338           C        BC-D  7981701352  9849591767   
58          A        338           C        BC-A  9347650766  9133608476   
59          A        338           M           -  8688239496  9247380475   
60          A        338           M        BC-B  9505057270  9346297270   

                           Unnamed: 14       Unnamed: 15  \
51                     INFO@IARE.AC.IN  FEE-NOT-EXEMPTED   
52                     INFO@IARE.AC.IN  FEE-NOT-EXEMPTED   
53       VARUNJAKKAMPUDI2322@GMAIL.COM  FEE-NOT-EXEMPTED   
54           VEERLAVARUN2003@GMAIL.COM  FEE-NOT-EXEMPTED   
55              vasudakamari@gmail.com      FEE-EXEMPTED   
56                     INFO@IARE.AC.IN  FEE-NOT-EXEMPTED   
57           dasariakhil4518@gmail.com      FEE-EXEMPTED   
58  VISHNUVARDHANKALLAGUNTA4@GMAIL.COM      FEE-EXEMPTED   
59                     INFO@IARE.AC.IN  FEE-NOT-EXEMPTED   
60                  nallojuy@gmail.com  FEE-NOT-EXEMPTED   

                  Unnamed: 16 Unnamed: 17 Unnamed: 18  
51  2222-Feb-2003200320032003    Studying         R20  
52  2828-Sep-2003200320032003    Studying         R20  
53  1616-Nov-2003200320032003    Studying         R20  
54  1111-May-2003200320032003    Studying         R20  
55  2020-Mar-2002200220022002    Studying         R20  
56  0404-Dec-2002200220022002    Studying         R20  
57  1010-Dec-2002200220022002    Studying         R20  
58  0505-Jul-2002200220022002    Studying         R20  
59  2121-Apr-2003200320032003    Studying         R20  
60  2121-Aug-2002200220022002    Studying         R20

In [3]:
def print_formatted(number):
    # your code goes here
    a=n
    b=bin(a)
    c=oct(a)
    d=hex(a)
    for i in range(0,n):
        return ("/n {} {} {} {}".format(a[i],c[i],d[i],b[i]))

if __name__ == '__main__':
    n = int(input())
    print_formatted(n)

5


TypeError: 'int' object is not subscriptable